print("Haloo Siapa nama Kamu ?")
nama = input("masukan nama:")
print("Dimana Kamu Tinggal ?")
alamat = input("masukan alamat :")
print("Berapa Umur Kamu?")
umur = input("masukan umur:")
print("Dimana Kamu Lahir?")
lahir = input('masukan tempat lahir :')
print("senang bertemu denganmu",nama, "dari",alamat,"umur :",umur,"tempat lahir di :", lahir)